### PR TITLE
Refactoring/type hints

### PR DESCRIPTION
**Pull request by dantp-ai**
This PR solves #95

Development environment

```
3.8.10 (default, Jan  5 2024, 09:18:58)
[Clang 15.0.0 (clang-1500.1.0.2.5)] darwin
```
---

- [x] Ran mypy
- [x] Ran tests
- [x] Ran pre-commit

### CODE REVIEW

**Comment by dantp-ai** [comment]
I developed and tested successfully on Python 3.8.10. 

Upon opening this PR, the tests seem to have failed for Python 3.9. When running mypy it finds 25 errors in 20 files (checked 297 source files).

So, I ran mypy also on the latest commit that is not part of this PR and the same number of errors were found. Can it be that the source code on main has not yet been tested on Python 3.9?

If so, I think it's best to resolve these 25 issues in a different PR and block the current PR until the other one has successfully been merged. Thoughts?

**Comment by sash-a** [comment]
I'll have a look into the mypy issue :smile:

**Review by sash-a — APPROVED** [review]
Thanks for this :smile:

**Comment by dantp-ai** [comment]
My pleasure. I thought it's a good first issue.

I see that you opened PR https://github.com/instadeepai/jumanji/pull/216. Once that is approved, hopefully the linting is gonna pass here too and we can merge.

**Review by clement-bonnet — APPROVED** [review]
Awesome, thank you for the improvement!

**Pull request merged**
