### PR TITLE
fix: make autoreset wrapper return 2 on reset

### PR DESCRIPTION
**Pull request by rodSiry**
Fixed the bad autoreset behavior described in issue #106 

Now, wrapped environment returns step_type = 2 when resetting.

Adapted corresponding test function, with assert step_type == 2.

### CODE REVIEW

**Review by dluo96 — CHANGES_REQUESTED** [review]
Thank you for your contribution @rodSiry! 🚀  This looks good to me! Could you update the PR title to follow the conventional commit style format (see our [contribution guidelines](https://github.com/instadeepai/jumanji/blob/main/CONTRIBUTING.md#coding-style)) and to be more informative? For example: `fix: make autoreset wrapper return 2 on reset`.

**Review by dluo96 — DISMISSED** [review]

**Comment by clement-bonnet** [comment]
Hi, thanks for the contribution. Would you mind applying the same fix to the `VmapAutoResetWrapper`? By saying so, I realize we should have shared some code between the two...
Thanks again!

**Review by clement-bonnet — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution. Would you mind applying the same fix to the `VmapAutoResetWrapper`? By saying so, I realize we should have shared some code between the two...
Thanks again!

**Review by clement-bonnet — CHANGES_REQUESTED** [review]
Looks good to me! One last thing I noticed: we need to update the class docstring of `AutoResetWrapper` to account for not resetting the step_type to FIRST anymore. Would you mind doing so? Thanks!

**Review by clement-bonnet — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
