### PR TITLE
fix: gh runners to use on-prem.

### PR DESCRIPTION
**Pull request by callumtilbury**
As per @alaterre's request. I think I've done everything correctly—will check when the PR opens, as I can't run self-hosted CI jobs from my personal acc 😅

### CODE REVIEW

**Comment by clement-bonnet** [comment]
Hey! Thanks for the PR. Just wondering, why are we doing that?

**Comment by callumtilbury** [comment]
Hey @clement-bonnet! Alex has asked us to use self-hosted runners for all InstaDeep CI—perhaps he can clarify 👍🏻

**Comment by callumtilbury** [comment]
> I wonder if this is the right thing to do here

It's a good question, @clement-bonnet. Still waiting to hear back from @alaterre.

In the interim, it's worth noting that the CI jobs aren't being picked up:
image
I may have made a syntax error somewhere, but the CI jobs _are_ running on other ID projects.

**Comment by clement-bonnet** [comment]
@callumtilbury do we have an update on this? I'm closing this for now but please reopen if we have an update :)

**Comment by callumtilbury** [comment]
thanks @clement-bonnet! Following up with @alaterre now :)

**Pull request closed without merging**
